all:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            picase01:
              ansible_host: 192.168.1.10
              ansible_user: picase01
              ansible_python_interpreter: /usr/bin/python3.12
              node_name: picase01
            picase02:
              ansible_host: 192.168.1.20
              ansible_user: picase02
              ansible_python_interpreter: /usr/bin/python3.12
              node_name: picase02
            picase03:
              ansible_host: 192.168.1.30
              ansible_user: picase03
              ansible_python_interpreter: /usr/bin/python3.12
              node_name: picase03
        worker:
          hosts:
            picase04:
              ansible_host: 192.168.1.40
              ansible_user: picase04
              ansible_python_interpreter: /usr/bin/python3.12
              node_name: picase04
            picase05:
              ansible_host: 192.168.1.50
              ansible_user: picase05
              ansible_python_interpreter: /usr/bin/python3.12
              node_name: picase05
