---
- name: Prepare Raspberry Pi nodes for K3s
  hosts: k3s_cluster
  roles:
      - role: prepare
        become: true

- name: Deploy K3s to control plane nodes
  hosts: master
  roles:
      - role: k3s-master
        become: true

- name: Deploy K3s to worker nodes
  hosts: worker
  roles:
      - role: k3s-worker
        become: true

- name: Setup K3s for access
  hosts: all
  roles:
      - role: k3s-setup
        become: true
